name: Monitor Actos ABC

on:
 # schedule:
  # - cron: '0 14 * * 1-5'
  # - cron: '0 21 * * 1-5'
 #  - cron: '0 1 * * 2-6'
  workflow_dispatch:

jobs:
  run-bot:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install twilio

      - name: Run bot
        run: python main.py
        env:
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
          TWILIO_FROM: ${{ secrets.TWILIO_FROM }}
          TWILIO_TO: ${{ secrets.TWILIO_TO }}

      - name: Commit cache
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git pull
          git add enviados.json || true
          git commit -m "update cache" || true
          git push

      # BORRAR CACHE DESPUÉS DEL RUN DE LAS 22 ARG
      - name: Reset cache at night
        if: github.event.schedule == '0 1 * * 2-6'
        run: |
          echo "[]" > enviados.json
          git add enviados.json
          git commit -m "reset cache" || true
          git push
