name: Monitor APD

on:
  schedule:
    - cron: "*/15 * * * *"   # cada 15 minutos
  workflow_dispatch:

jobs:
  run-script:

    runs-on: ubuntu-latest

    steps:

      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Instalar navegadores Playwright
        run: playwright install

      - name: Ejecutar bot
        run: python main.py
        env:
          ABC_USER: ${{ secrets.ABC_USER }}
          ABC_PASS: ${{ secrets.ABC_PASS }}
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
          TWILIO_FROM: ${{ secrets.TWILIO_FROM }}
          TWILIO_TO: ${{ secrets.TWILIO_TO }}
