name: Monitor Actos ABC

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  run:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install deps
      run: |
        pip install -r requirements.txt
        playwright install chromium

    - name: Run script
      env:
        TWILIO_SID: ${{ secrets.TWILIO_SID }}
        TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
        TWILIO_FROM: ${{ secrets.TWILIO_FROM }}
        TWILIO_TO: ${{ secrets.TWILIO_TO }}
      run: python main.py
